// AUTOGENERATED FILE 2024-01-17 16:02:45.845119

// ---- Scenario tree

// -- Type
// is tree generated by a stopped Markov process?
bool const _is_markovian = true;
// is tree generated by an independent and identically distributed sequence?
bool const _is_iid = false;

// -- Attributes
// total number of nonleaf nodes
const int _num_nonleaf_nodes = 3;
// total number of nodes
const int _num_nodes = 7;
// total number of stages (N+1)
const int _num_stages = 3;
// array of stage of node at index
const int stages[7] = {0,1,1,2,2,2,2,};
// array of ancestor of node at index
const int ancestors[7] = {-1,0,0,1,1,2,2,};
// array of probability of visiting node at index
const double probability[7] = {1.0,0.6,0.4,0.3,0.3,0.2,0.2,};
// array of event occurred that led to node at index
const int events[7] = {-1,0,1,0,1,0,1,};
// vector of children of node 0
vector<const int> ch_of_0{1,2,};
// vector of children of node 1
vector<const int> ch_of_1{3,4,};
// vector of children of node 2
vector<const int> ch_of_2{5,6,};
// array of pointer-to-vectors of children of node at index
vector<const int> children[3] = {ch_of_0,ch_of_1,ch_of_2,};
 