// AUTOGENERATED FILE 2024-01-15 19:09:01.015743

#pragma once
#include <vector>
using namespace std;

// ---- Scenario tree

// Type
bool const markovian = true;

// Attributes
const int num_nonleaf_nodes = 3;
const int num_nodes = 7;
const int num_stages = 3;
const int stages[7] = {0,1,1,2,2,2,2,};
const int ancestors[7] = {-1,0,0,1,1,2,2,};
const double probability[7] = {1.0,0.6,0.4,0.3,0.3,0.2,0.2,};
const int events[7] = {-1,0,1,0,1,0,1,};
vector<const int> ch_of_0{1,2,};
vector<const int> ch_of_1{3,4,};
vector<const int> ch_of_2{5,6,};
vector<const int> children[3] = {ch_of_0,ch_of_1,ch_of_2,};
 