// AUTOGENERATED FILE 2024-01-16 14:13:40.614050

#pragma once
#include <vector>
using namespace std;

// ---- Scenario tree

// Type
bool const markovian = true;

// Attributes
const int num_nonleaf_nodes = 7;
const int num_nodes = 10;
const int num_stages = 4;
const int stages[10] = {0,1,1,1,2,2,2,3,3,3,};
const int ancestors[10] = {-1,0,0,0,1,2,3,4,5,6,};
const double probability[10] = {1.0,0.5,0.4,0.1,0.5,0.4,0.1,0.5,0.4,0.1,};
const int events[10] = {-1,0,1,2,0,1,2,0,1,2,};
vector<const int> ch_of_0{1,2,3,};
vector<const int> ch_of_1{4,};
vector<const int> ch_of_2{5,};
vector<const int> ch_of_3{6,};
vector<const int> ch_of_4{7,};
vector<const int> ch_of_5{8,};
vector<const int> ch_of_6{9,};
vector<const int> children[7] = {ch_of_0,ch_of_1,ch_of_2,ch_of_3,ch_of_4,ch_of_5,ch_of_6,};
 