// AUTOGENERATED FILE 2024-01-13 14:48:09.632105

// ---- Scenario tree

// Type
bool is_markovian = true;

// Attributes
int num_nonleaf_nodes = 3;
int num_nodes = 7;
int num_stages = 3;
int stages[7] = {0,1,1,2,2,2,2,};
int ancestors[7] = {-1,0,0,1,1,2,2,};
double probability[7] = {1.0,0.6,0.4,0.3,0.3,0.2,0.2,};
int events[7] = {-1,0,1,0,1,0,1,};
int children[3] = {2,4,6,};
 