on:
  push:
    branches: [ main ]
  pull_request:

name: Continuous integration

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: install cuda toolkit 12.3.x
        uses: Jimver/cuda-toolkit@v0.2.14
        id: cuda-toolkit
        with:
          cuda: '12.3.2'
          method: 'network'
          sub-packages: '["nvcc"]'
      - name: check gpu allocation
        run: |
            nvidia-smi

      - run: bash ./ci/script.sh

